// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'b9167d79eb88f7c4d28b8fc10ccd0fc351dad70b9676f8f10154beabedfe6a4d'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Answers: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly questionId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly optionId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Favorites: {
      readonly videoId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Likes: {
      readonly videoId: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
    };
    readonly Options: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly questionId: CodecTypes['pg/uuid@1']['output'];
      readonly option: Varchar<255>;
    };
    readonly Questions: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly surveyId: CodecTypes['pg/uuid@1']['output'];
      readonly label: Varchar<255>;
    };
    readonly Surveys: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly createdBy: CodecTypes['pg/uuid@1']['output'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly title: Varchar<255>;
      readonly description: Varchar<255> | null;
    };
    readonly Users: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly firstname: Varchar<255>;
      readonly lastname: Varchar<255>;
      readonly email: Varchar<255>;
      readonly password: Varchar<255>;
      readonly role: 'jobseeker' | 'recruiter' | 'admin';
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly birthdate: CodecTypes['pg/timestamp-temporal@1']['output'];
    };
    readonly Videos: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly userId: CodecTypes['pg/uuid@1']['output'];
      readonly videoLink: Varchar<255>;
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Answers: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly questionId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly optionId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Favorites: {
      readonly videoId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Likes: {
      readonly videoId: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
    };
    readonly Options: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly questionId: CodecTypes['pg/uuid@1']['input'];
      readonly option: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Questions: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly surveyId: CodecTypes['pg/uuid@1']['input'];
      readonly label: CodecTypes['sql/varchar@1']['input'];
    };
    readonly Surveys: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly createdBy: CodecTypes['pg/uuid@1']['input'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly title: CodecTypes['sql/varchar@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
    };
    readonly Users: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly firstname: CodecTypes['sql/varchar@1']['input'];
      readonly lastname: CodecTypes['sql/varchar@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly password: CodecTypes['sql/varchar@1']['input'];
      readonly role: 'jobseeker' | 'recruiter' | 'admin';
      readonly createdAt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly birthdate: CodecTypes['pg/timestamp-temporal@1']['input'];
    };
    readonly Videos: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly userId: CodecTypes['pg/uuid@1']['input'];
      readonly videoLink: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly answers: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly option_id: CodecTypes['pg/uuid@1']['output'];
      readonly question_id: CodecTypes['pg/uuid@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly favorites: {
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly video_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly likes: {
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly video_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly options: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly option: Varchar<255>;
      readonly question_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly questions: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly label: Varchar<255>;
      readonly survey_id: CodecTypes['pg/uuid@1']['output'];
    };
    readonly surveys: {
      readonly created_by: CodecTypes['pg/uuid@1']['output'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly description: Varchar<255> | null;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly title: Varchar<255>;
    };
    readonly users: {
      readonly birthdate: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly email: Varchar<255>;
      readonly firstname: Varchar<255>;
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly lastname: Varchar<255>;
      readonly password: Varchar<255>;
      readonly role: 'jobseeker' | 'recruiter' | 'admin';
    };
    readonly videos: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly user_id: CodecTypes['pg/uuid@1']['output'];
      readonly video_link: Varchar<255>;
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly answers: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly option_id: CodecTypes['pg/uuid@1']['input'];
      readonly question_id: CodecTypes['pg/uuid@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly favorites: {
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly video_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly likes: {
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly video_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly options: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly option: CodecTypes['sql/varchar@1']['input'];
      readonly question_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly questions: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly label: CodecTypes['sql/varchar@1']['input'];
      readonly survey_id: CodecTypes['pg/uuid@1']['input'];
    };
    readonly surveys: {
      readonly created_by: CodecTypes['pg/uuid@1']['input'];
      readonly date: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly description: CodecTypes['sql/varchar@1']['input'] | null;
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly title: CodecTypes['sql/varchar@1']['input'];
    };
    readonly users: {
      readonly birthdate: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly email: CodecTypes['sql/varchar@1']['input'];
      readonly firstname: CodecTypes['sql/varchar@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly lastname: CodecTypes['sql/varchar@1']['input'];
      readonly password: CodecTypes['sql/varchar@1']['input'];
      readonly role: 'jobseeker' | 'recruiter' | 'admin';
    };
    readonly videos: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly user_id: CodecTypes['pg/uuid@1']['input'];
      readonly video_link: CodecTypes['sql/varchar@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly answers: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly question_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly option_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'answers_pkey' };
              uniques: readonly [
                {
                  readonly columns: readonly ['question_id', 'user_id'];
                  readonly name: 'answers_question_id_user_id_key';
                },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'answers';
                    readonly columns: readonly ['option_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'options';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'answers_option_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'answers';
                    readonly columns: readonly ['question_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'questions';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'answers_question_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'answers';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'answers_user_id_fkey';
                },
              ];
            };
            readonly favorites: {
              columns: {
                readonly video_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['video_id', 'user_id'];
                readonly name: 'favorites_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'favorites';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'favorites_user_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'favorites';
                    readonly columns: readonly ['video_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'videos';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'favorites_video_id_fkey';
                },
              ];
            };
            readonly likes: {
              columns: {
                readonly video_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['video_id', 'user_id'];
                readonly name: 'likes_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'likes';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'likes_user_id_fkey';
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'likes';
                    readonly columns: readonly ['video_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'videos';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'likes_video_id_fkey';
                },
              ];
            };
            readonly options: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly question_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly option: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'options_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'options';
                    readonly columns: readonly ['question_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'questions';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'options_question_id_fkey';
                },
              ];
            };
            readonly questions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly survey_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly label: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'questions_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'questions';
                    readonly columns: readonly ['survey_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'surveys';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'questions_survey_id_fkey';
                },
              ];
            };
            readonly surveys: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly created_by: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly date: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
                readonly title: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly description: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: true;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'surveys_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'surveys';
                    readonly columns: readonly ['created_by'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'surveys_created_by_fkey';
                },
              ];
            };
            readonly users: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly firstname: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly lastname: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly email: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly password: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
                readonly role: {
                  readonly nativeType: 'user_role';
                  readonly codecId: 'pg/enum@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly typeName: 'user_role' };
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
                readonly birthdate: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'users_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly videos: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly user_id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                };
                readonly video_link: {
                  readonly nativeType: 'character varying';
                  readonly codecId: 'sql/varchar@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly length: 255 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'videos_pkey' };
              uniques: readonly [
                { readonly columns: readonly ['user_id']; readonly name: 'videos_user_id_key' },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'videos';
                    readonly columns: readonly ['user_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'users';
                    readonly columns: readonly ['id'];
                  };
                  readonly name: 'videos_user_id_fkey';
                },
              ];
            };
          };
          readonly valueSet: {
            readonly UserRole: {
              readonly kind: 'valueSet';
              readonly values: readonly ['jobseeker', 'recruiter', 'admin'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly users: { readonly namespace: 'public' & NamespaceId; readonly model: 'Users' };
    readonly surveys: { readonly namespace: 'public' & NamespaceId; readonly model: 'Surveys' };
    readonly questions: { readonly namespace: 'public' & NamespaceId; readonly model: 'Questions' };
    readonly options: { readonly namespace: 'public' & NamespaceId; readonly model: 'Options' };
    readonly answers: { readonly namespace: 'public' & NamespaceId; readonly model: 'Answers' };
    readonly videos: { readonly namespace: 'public' & NamespaceId; readonly model: 'Videos' };
    readonly favorites: { readonly namespace: 'public' & NamespaceId; readonly model: 'Favorites' };
    readonly likes: { readonly namespace: 'public' & NamespaceId; readonly model: 'Likes' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Answers: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly optionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly option: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Options';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['optionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Questions';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['questionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'answers';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly questionId: { readonly column: 'question_id' };
                readonly userId: { readonly column: 'user_id' };
                readonly optionId: { readonly column: 'option_id' };
              };
            };
          };
          readonly Favorites: {
            readonly fields: {
              readonly videoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly video: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Videos';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['videoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'favorites';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly videoId: { readonly column: 'video_id' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly Likes: {
            readonly fields: {
              readonly videoId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly video: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Videos';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['videoId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'likes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly videoId: { readonly column: 'video_id' };
                readonly userId: { readonly column: 'user_id' };
              };
            };
          };
          readonly Options: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly option: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly answers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Answers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['optionId'];
                };
              };
              readonly question: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Questions';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['questionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'options';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly questionId: { readonly column: 'question_id' };
                readonly option: { readonly column: 'option' };
              };
            };
          };
          readonly Questions: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly surveyId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly label: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly answers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Answers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['questionId'];
                };
              };
              readonly options: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Options';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['questionId'];
                };
              };
              readonly survey: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Surveys';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['surveyId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'questions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly surveyId: { readonly column: 'survey_id' };
                readonly label: { readonly column: 'label' };
              };
            };
          };
          readonly Surveys: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly createdBy: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly description: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly questions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Questions';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['surveyId'];
                };
              };
              readonly users: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['createdBy'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'surveys';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly createdBy: { readonly column: 'created_by' };
                readonly date: { readonly column: 'date' };
                readonly title: { readonly column: 'title' };
                readonly description: { readonly column: 'description' };
              };
            };
          };
          readonly Users: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly firstname: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly lastname: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly password: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
              readonly role: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/enum@1';
                  readonly typeParams: { readonly typeName: 'user_role' };
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              readonly birthdate: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
            };
            readonly relations: {
              readonly answers: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Answers';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly favorites: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Favorites';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly likes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Likes';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly surveys: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Surveys';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['createdBy'];
                };
              };
              readonly videos: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Videos';
                };
                readonly cardinality: '1:1';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'users';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly firstname: { readonly column: 'firstname' };
                readonly lastname: { readonly column: 'lastname' };
                readonly email: { readonly column: 'email' };
                readonly password: { readonly column: 'password' };
                readonly role: { readonly column: 'role' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly birthdate: { readonly column: 'birthdate' };
              };
            };
          };
          readonly Videos: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly videoLink: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'sql/varchar@1';
                  readonly typeParams: { readonly length: 255 };
                };
              };
            };
            readonly relations: {
              readonly favorites: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Favorites';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['videoId'];
                };
              };
              readonly likes: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Likes';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['videoId'];
                };
              };
              readonly user: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Users';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'videos';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly userId: { readonly column: 'user_id' };
                readonly videoLink: { readonly column: 'video_link' };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
